name: EnableKafkaPlugin
group: test
version: 1.0.0

install:
  - name: copy plugin file
    copy:
      src: kafka/config/plugin/registry/KafkaMessageTransport.gwp
      dest: modules/configuration/config/plugin/registry/KafkaMessageTransport.gwp

  - name: copy messaging file
    copy:
      src: kafka/config/messaging/messaging-config.xml
      dest: modules/configuration/config/messaging/messaging-config.xml
